platform :ios, '7.0'
pod 'ReactiveCocoa'
pod 'Expecta', inhibit_warnings: true
pod 'Specta'
pod 'CocoaAsyncSocket'
pod 'CocoaLumberjack'
pod 'KissXML'
pod 'OpenSSL', podspec: 'podspecs/OpenSSL.podspec'
pod 'NetPGP', podspec: 'podspecs/NetPGP.podspec'
pod 'SSKeychain'
pod 'OCMock'
